### ISSUE TITLE
Duplicate node name in graph: 'ones'

### ISSUE THREAD

**Issue by Israel-Lopez-Herreros** [pythonlessons/TensorFlow-2.x-YOLOv3#64] opened 2020-09-24 10:10 UTC
Hi,

I have the following error testing the yolov3 example: https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3

2020-09-24 11:28:23.492471: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'ones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev\pydevd.py", line 1683, in
main()
File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev\pydevd.py", line 1677, in main
globals = debugger.run(setup['file'], None, None, is_module)
File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev\pydevd.py", line 1087, in run
pydev_imports.execfile(file, globals, locals) # execute the script
File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master/detection_demo.py", line 22, in
yolo = Load_Yolo_model()
File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master\yolov3\utils.py", line 84, in Load_Yolo_model
yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=YOLO_COCO_CLASSES)
File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master\yolov3\yolov4.py", line 398, in Create_Yolo
pred_tensor = decode(conv_tensor, NUM_CLASS, i)
File "C:/Users/c81441/Documents/75-GIT-PYTHON-PHOTOGRAMMETRY/deep_learning/20-TensorFlow-2.x-YOLOv3-master\yolov3\yolov4.py", line 427, in decode
xy_grid = tf.meshgrid(tf.range(output_size), tf.range(output_size))
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2954, in meshgrid
mult_fact = ones(shapes, output_dtype)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 2583, in ones
output = fill(shape, constant(one, dtype=dtype), name=name)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 171, in fill
result = gen_array_ops.fill(dims, value, name=name)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 3601, in fill
"Fill", dims=dims, value=value, name=name)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
op_def=op_def)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 548, in create_op
compute_device)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
op_def=op_def)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1773, in init
control_input_ops)
File "C:\Users\c81441\AppData\Local\Continuum\Anaconda3_64_2020_02\envs\tensor_flow_env_test\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1613, in _create_c_op
raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'ones'

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7, 64bits
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 2.0.0. I have tested with different tf/pythons versions and I get the same error
Python version: 3.6.9
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: NA
GPU model and memory: NA

**Comment by bhack** [comment] 2020-09-24 11:54
It seems a duplicate of https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3/issues/37

**Comment by chrisTopp84** [comment] 2020-10-08 13:07
@bhack: I have looked into #37 and left a comment there. But I don't know if this is possible.
I also have this problem 

> ValueError: Duplicate node name in graph: 'ones'
and I could not find a solution in #37 that worked for me. Maybe it's the same for Israel-Lopez-Herreros.

I'm using a Jetson Nano with Jetpack 4.3 and the problem is that this Jetpack version is only compatible with TF 2.1.0 or lower (the version I use is TF 2.1.0).
TF 2.2 or TF 2.3 are not compatible with Jetpack 4.3.

So I would be interested if there is a solution for the problem without changing the TF version to 2.2 or 2.3.

Best regards

**Comment by pythonlessons** [comment] 2020-10-08 13:51
Yolov3 should work with TF2.1, so you can test. Yolov4 is not working with lower versions than TF2.3 but I can't guarantee

**Comment by chrisTopp84** [comment] 2020-10-08 14:28
Unfortunately it is not working on my jetson nano. When i want to use Yolov3 Tiny the configs.py file looks like this:
TRAIN_YOLO_TINY is set to True

```
#================================================================
#
#   File name   : configs.py
#   Author      : PyLessons
#   Created date: 2020-08-18
#   Website     : https://pylessons.com/
#   GitHub      : https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3
#   Description : yolov3 configuration file
#
#================================================================

# YOLO options
YOLO_TYPE                   = "yolov3" # yolov4 or yolov3
YOLO_FRAMEWORK              = "tf" # "tf" or "trt"
YOLO_V3_WEIGHTS             = "model_data/yolov3.weights"
YOLO_V4_WEIGHTS             = "model_data/yolov4.weights"
YOLO_V3_TINY_WEIGHTS        = "model_data/yolov3-tiny.weights"
YOLO_V4_TINY_WEIGHTS        = "model_data/yolov4-tiny.weights"
YOLO_TRT_QUANTIZE_MODE      = "INT8" # INT8, FP16, FP32
YOLO_CUSTOM_WEIGHTS         = False # "checkpoints/yolov3_custom" # used in evaluate_mAP.py and custom model detection, if not using leave False
                            # YOLO_CUSTOM_WEIGHTS also used with TensorRT and custom model detection
YOLO_COCO_CLASSES           = "model_data/coco/coco.names"
YOLO_STRIDES                = [8, 16, 32]
YOLO_IOU_LOSS_THRESH        = 0.5
YOLO_ANCHOR_PER_SCALE       = 3
YOLO_MAX_BBOX_PER_SCALE     = 100
YOLO_INPUT_SIZE             = 416
if YOLO_TYPE                == "yolov4":
    YOLO_ANCHORS            = [[[12,  16], [19,   36], [40,   28]],
                               [[36,  75], [76,   55], [72,  146]],
                               [[142,110], [192, 243], [459, 401]]]
if YOLO_TYPE                == "yolov3":
    YOLO_ANCHORS            = [[[10,  13], [16,   30], [33,   23]],
                               [[30,  61], [62,   45], [59,  119]],
                               [[116, 90], [156, 198], [373, 326]]]
# Train options
# AENDERUNG IN DER NACHFOLGENDEN ZEILE VORGENOMMEN
TRAIN_YOLO_TINY             = True # temporaer von False auf True geändert
TRAIN_SAVE_BEST_ONLY        = True # saves only best model according validation loss (True recommended)
TRAIN_SAVE_CHECKPOINT       = False # saves all best validated checkpoints in training process (may require a lot disk space) (False recommended)
TRAIN_CLASSES               = "mnist/mnist.names"
TRAIN_ANNOT_PATH            = "mnist/mnist_train.txt"
TRAIN_LOGDIR                = "log"
TRAIN_CHECKPOINTS_FOLDER    = "checkpoints"
TRAIN_MODEL_NAME            = f"{YOLO_TYPE}_custom"
TRAIN_LOAD_IMAGES_TO_RAM    = True # With True faster training, but need more RAM
TRAIN_BATCH_SIZE            = 4
TRAIN_INPUT_SIZE            = 416
TRAIN_DATA_AUG              = True
TRAIN_TRANSFER              = True
TRAIN_FROM_CHECKPOINT       = False # "checkpoints/yolov3_custom"
TRAIN_LR_INIT               = 1e-4
TRAIN_LR_END                = 1e-6
TRAIN_WARMUP_EPOCHS         = 2
TRAIN_EPOCHS                = 100

# TEST options
TEST_ANNOT_PATH             = "mnist/mnist_test.txt"
TEST_BATCH_SIZE             = 4
TEST_INPUT_SIZE             = 416
TEST_DATA_AUG               = False
TEST_DECTECTED_IMAGE_PATH   = ""
TEST_SCORE_THRESHOLD        = 0.3
TEST_IOU_THRESHOLD          = 0.45


#YOLOv3-TINY and YOLOv4-TINY WORKAROUND
if TRAIN_YOLO_TINY:
    YOLO_STRIDES            = [16, 32, 64]    
    YOLO_ANCHORS            = [[[10,  14], [23,   27], [37,   58]],
                               [[81,  82], [135, 169], [344, 319]],
                               [[0,    0], [0,     0], [0,     0]]]
```

When I run 
`(yolov3Tensorflow) christopher@ccz:~/TensorFlow_2_x_YOLOv3$ python3 detection_demo.py `

this is the output

```
2020-10-08 16:23:00.004160: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-10-08 16:23:04.932070: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-10-08 16:23:04.951652: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2020-10-08 16:23:10.711011: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-10-08 16:23:10.765443: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:10.765600: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:00.0 name: NVIDIA Tegra X1 computeCapability: 5.3
coreClock: 0.9216GHz coreCount: 1 deviceMemorySize: 3.87GiB deviceMemoryBandwidth: 23.84GiB/s
2020-10-08 16:23:10.765731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-10-08 16:23:10.765873: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-10-08 16:23:10.783994: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-10-08 16:23:10.814263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-10-08 16:23:10.853993: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-10-08 16:23:10.872737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-10-08 16:23:10.873099: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-08 16:23:10.873536: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:10.873977: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:10.874080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
GPUs [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2020-10-08 16:23:11.000619: W tensorflow/core/platform/profile_utils/cpu_utils.cc:98] Failed to find bogomips in /proc/cpuinfo; cannot determine CPU frequency
2020-10-08 16:23:11.001244: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a693bf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-08 16:23:11.001302: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-08 16:23:11.156960: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:11.157542: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a5fa2e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-08 16:23:11.157630: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA Tegra X1, Compute Capability 5.3
2020-10-08 16:23:11.158606: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:11.158798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:00:00.0 name: NVIDIA Tegra X1 computeCapability: 5.3
coreClock: 0.9216GHz coreCount: 1 deviceMemorySize: 3.87GiB deviceMemoryBandwidth: 23.84GiB/s
2020-10-08 16:23:11.159076: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-10-08 16:23:11.159243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-10-08 16:23:11.159426: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-10-08 16:23:11.159738: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-10-08 16:23:11.159958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-10-08 16:23:11.160151: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-10-08 16:23:11.160292: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-08 16:23:11.160734: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:11.161187: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:11.161316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-10-08 16:23:11.161631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-10-08 16:23:17.453329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-08 16:23:17.453462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-10-08 16:23:17.453515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-10-08 16:23:17.454393: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:17.455070: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:948] ARM64 does not support NUMA - returning NUMA node zero
2020-10-08 16:23:17.455379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 116 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X1, pci bus id: 0000:00:00.0, compute capability: 5.3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1619, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'ones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detection_demo.py", line 22, in <module>
    yolo = Load_Yolo_model()
  File "/home/christopher/TensorFlow_2_x_YOLOv3/yolov3/utils.py", line 90, in Load_Yolo_model
    yolo = Create_Yolo(input_size=YOLO_INPUT_SIZE, CLASSES=YOLO_COCO_CLASSES)
  File "/home/christopher/TensorFlow_2_x_YOLOv3/yolov3/yolov4.py", line 398, in Create_Yolo
    pred_tensor = decode(conv_tensor, NUM_CLASS, i)
  File "/home/christopher/TensorFlow_2_x_YOLOv3/yolov3/yolov4.py", line 427, in decode
    xy_grid = tf.meshgrid(tf.range(output_size), tf.range(output_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 3065, in meshgrid
    mult_fact = ones(shapes, output_dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 2671, in ones
    output = fill(shape, constant(one, dtype=dtype), name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 233, in fill
    result = gen_array_ops.fill(dims, value, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3247, in fill
    "Fill", dims=dims, value=value, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1786, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'ones'
```

Something is going wrong but I have no idea if it has anything to do with tensorflow.

**Comment by pythonlessons** [comment] 2020-11-29 10:13
"ValueError: Duplicate node name in graph: 'ones'' fixed

**Closed by pythonlessons** 2020-11-29 10:13 UTC
